version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cicd
permissions: 
  - object: /home/ubuntu/cicd
    owner: ubuntu 
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/ins_os_dep.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/py_dep.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/gunicorn.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/nginx.sh
      timeout: 300
      runas: ubuntu
  # Applicationstart:
  #   - location: scripts/start.sh
  #     timeout: 300
  #     runas: ubuntu
  # Applicationstop:
  #   - location: scripts/stop.sh
  #     timeout: 300
  #     runas: ubuntu


